Remove implicit int declaration from a test
This didn't seem to be the point of the issue but caused the test to
fail.

Error message:
Common.TranslateAssertError@tests/unit/issues/Issue8.d(14):
Cannot compile source code. Errors:
----------------
 /tmp/dstepZRUFDHDGRGxkGPVu.h:22:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]